# module 1 for section1.1

# the assigment id
- assignment: e0008e0c1b4d7b8328f37e0ed5e43752  >>update
# the section from guides, to show both the Chapter and Section names
  section:  ["Chapter 1", "Section 1.1"]
# to include all files contained in the folder Section 1.1
  paths: ['Section 1.1/**'] 