# module 1 for section 2.1 and 2.2

# the assigment id
- assignment: 36f5f6d99f69a7dc12f2ce8d619e8494
  section:  ["Chapter 2", "Section 2.1"]
  paths: ['**']
# to include another section from guides in the assignment
- assignment: 36f5f6d99f69a7dc12f2ce8d619e8494
  section:  ["Chapter 2", "Section 2.2"]
# to include a specific file from the root folder
  paths: ['file3.java'] 